### ISSUE TITLE
Documentation on header support

### ISSUE THREAD

**Issue by mohantaylor** [nats-io/nats.ts#103]
Could you clarify what the server support is for headers? In the ts nats docs it simply states "Headers are enabled automatically if the server supports them" but I can't find docs on what the server support / minimum version is?

Thanks!

**Comment by aricart** [comment]
@mohantaylor headers are not available on currently released versions of the nats-server. It is available on docker nightly images. Also for the javascript clients, it is only supported in nats.ws, nats.js and nats.deno release candidates
