### ISSUE TITLE
Is one client per payload really necessary

### ISSUE THREAD

**Issue by jonaslagoni** [nats-io/nats.ts#60]
Hey!

I have a question or ponder regarding the connection option payload. I am working on implementing a template for NATS in typescript for AsyncAPI documents. However in their specification the payload type is defined [per operation](https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-messageobject-a-message-object) as a `contentType` field. To map this over to nats.ts would require a client per `contentType` used which I dont think is the most optimal way of doing it. 

Any suggestion on how I can resolve this? 😄

**Comment by aricart** [comment]
you would have to have as many clients (or create one on the fly) with the payload you require. That also means you probably need to carefully name the subjects that contain different payload types to avoid not expected payload/decoding errors.
