### ISSUE TITLE
check for tls certificate issue errors as in nats.js

### ISSUE THREAD

**Issue by aricart** [nats-io/nats.ts#61]
check https://github.com/nats-io/nats.js/pull/311 for possible impacts on nats.ts

https://github.com/nats-io/nats.js/issues/310

**Comment by labsvisual** [comment]
Hey! I was able to reproduce similar behavior on TypeScript since the underlying implementation in `TCPTransport.js` is the same:

https://github.com/nats-io/nats.ts/blob/079998b614edce55ca895127a19f2120e6b56376/src/tcptransport.ts#L102

The same fix should work here! 😄

**Comment by aricart** [comment]
Yes created that issue in response
