### ISSUE TITLE
Slow pending limits for consumers and handlers

### ISSUE THREAD

**Issue by BatiGencho** [nats-io/nats.ts#73]
Hi,

why is ts-client for NATS incapable of having a setter for pending limits and a handler to detect slow consumers? Can you introduce one in the ts.client ?

Thanks.

**Comment by aricart** [comment]
That would mean processing the buffer into a queue that could be queued. Right now the ingestion mechanism simply looks for the first protocol it can find and dispatches.

**Comment by BatiGencho** [comment]
Ok, thanks for the explanation. I do get your point. The problem we are having is that we are running 10x ++ replicas of a node worker that is subscribed to a certain topic over a queue, suggesting that the dispatch will be done in a round robin manner with a very fast consumption on our side as we fetch the callback and do async promise straight away. It looks however that NATS is dropping messages as our results are not correct. We have not tried spinning up 100 instances of the worker yet, but we had the chance to compare it to the same implementation in golang, where with very high buffers the dropped messages disappeared (at least we have a handler ther to see that). What if we use nats-straming ? Could you help us what it is exactly and whether this would help us

**Comment by aricart** [comment]
@BatiGencho how many messages are you generating per second vs processing? NATS will do millions of messages per second without breaking a sweat. But if you are producing more than your workers can process, at some point workers are going to be slow consumers. If all your workers are part of the queue group, then the server load balances, however, unless you dynamically adjust for when you have heavy workloads, you will run into the same issue. BTW, you could potentially have another service monitor traffic (simply subscribing outside of that queue group) and when the message rate increases more than your workers can handle comfortably you can add additional workers.

NATS streaming is the opposite of NATS (internally we call it STAN). NATS streaming stores messages in a channel (one subject = one channel), and replays them to a subscriber. The logs are persistent, meaning that old messages will linger as per the store expiration policy.

As with NATS, you can create queue subscribers to manage the load, and you can also make your subscribers durable. The server retains the durable subscribers (or group) position, so on a restart of the client, work resumes with the last un-acknowledged message.

To make nats-streaming work queue, you would:

- create a durable queue subscription
- set acknowledgment of message to manual
- set `maxInFlight` to 1 - this will make the server only send a single message to a client at a time.
- set your acknowledgment wait to be longer than the time required to process a message under load.

The client would then receive a message process it, and when done acknowledge it. At that point, the server will send another.

Note that there are many trade-offs. Message streams persist using some sort of policy, and it is possible that if some process takes longer to acknowledge the message than what was set the message would be sent to another for processing. This means that your processing would likely require some way to handle duplicates (nats streaming will inform you that it is a duplicate send). Again NATS is at most once, NATS Streaming is at least once.

**Comment by aricart** [comment]
Also note that messages are stored in a queue and it is just a replay - meaning that there's no request-reply when you have nats-streaming. You are simply processing the log.

**Comment by aricart** [comment]
Finally - we are working on a new technology dubbed JetStream, that uses plain nats messages and supports worker semantics. See https://nats.io/blog/tech-preview-oct-2019/
