### ISSUE TITLE
Any Release Soon?

### ISSUE THREAD

**Issue by beeing** [nats-io/nats.ts#77]
Hi, noticed there are some fixes added but there's no official release yet.

Any indication when will there be an update in npm?

Thanks.

**Comment by aricart** [comment]
Funny you should ask, working on the release right now. Current master is available under `npm install ts-nats@next`

**Comment by beeing** [comment]
Thanks!

**Comment by aricart** [comment]
@beeing  - just made 1.2.12 - https://github.com/nats-io/nats.ts/releases/tag/v1.2.12
