### ISSUE TITLE
In version 1.2.12 the method of finding package.json is causing problems

### ISSUE THREAD

**Issue by CycoPH** [nats-io/nats.ts#87]
The version 1.2.12 on npm has this code:
let pkgFile = __dirname + '/../package.json';
if (!fs_1.existsSync(pkgFile)) {
    // tests will find it here
    pkgFile = __dirname + '/../../package.json';
}

This fails on non-unix based systems. Should use the path helper to build the path.

**Comment by aricart** [comment]
@CycoPH this has been since fixed in master. You can reference `npm install ts-nats@next`.
